name: Bug Report
description: Report a bug with textfox
labels: ["bug"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight checklist
      options:
        - label: I have searched existing issues and this has not been reported before
          required: true
        - label: I am using the latest version of textfox (pulled from main)
          required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
    validations:
      required: true
